---
- include: configuration_mysql_dir.yml

- name: install mysql system files
  command:
    mysql_install_db --user=mysql --datadir="{{ percona_mysql_data_dir.value }}"
    creates="{{ percona_mysql_data_dir.value }}/mysql"

- name: copy plugins my.cnf
  template:
    src="plugins.cnf.j2"
    dest=/etc/mysql/conf.d/plugins.cnf
    owner=mysql
    group=mysql
    mode=0640
    seuser=system_u
    serole=object_r
    setype=mysqld_etc_t
    selevel=s0
  notify:
    - restart mysql
#    - Update percona_mysql_tokudb_variables
#    - Update percona_mysql_percona_audit_logging_variables

- name: copying mysql.server init script to make startup script consistent across distributions
  template:
    src="mysql.server.j2"
    dest=/etc/init.d/mysql
    owner=root
    group=root
    mode=0755
    seuser=system_u
    serole=object_r
    setype=initrc_exec_t
    selevel=s0
  tags: percona_mysql_manage_init_script
  
- name: ensure mysql has been stopped after the upgrade
  service:
    name="{{ percona_mysql_service_name }}"
    state=stopped
  when: percona_mysql_upgrade and (percona_mysql_pkg_check_redhat.changed or percona_mysql_pkg_check_debian.changed)

- name: Make sure mysql is listening
  lineinfile: dest=/etc/mysql/my.cnf regexp="^bind-address" line="#bind-address            = 127.0.0.1" state=present
  
- name: start mysql
  service:
    name="{{ percona_mysql_service_name }}"
    state=started
    enabled=yes

- include: set_root_password.yml
  when: (percona_mysql_pkg_check_redhat.changed or percona_mysql_pkg_check_debian.changed)

- include: install_plugins.yml

- name: optionally execute mysql_upgrade after an upgrade has been performed
  command:
    mysql_upgrade --skip-write-binlog
  when: percona_mysql_check_upgrade and (percona_mysql_pkg_check_redhat.changed or percona_mysql_pkg_check_debian.changed)

- name: Ensure the correct version of percona is installed
  command: mysql --version
  register: command_result
  changed_when: False
  failed_when: command_result.stdout.find('"{{percona_mysql_server_version}}"') != -1

