---

- name: update root password
  mysql_user:
    name=root
    host=localhost
    password="{{ percona_mysql_root_password|default(lookup('password', '/tmp/percona_mysql/' + inventory_hostname + '_percona_mysql_root_password_file length=12 chars=ascii_letters,digits'), true) }}"
    login_unix_socket=/var/run/mysqld/mysqld.sock

- name: remove anonymous users
  mysql_user:
    name=''
    host={{ item }}
    state=absent
    login_user=root
    login_password="{{ percona_mysql_root_password|default(lookup('password', '/tmp/percona_mysql/' + inventory_hostname + '_percona_mysql_root_password_file length=12 chars=ascii_letters,digits'), true) }}"
    login_unix_socket=/var/run/mysqld/mysqld.sock
  with_items:
      - localhost
      - "{{ ansible_hostname }}"